steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - descrypt
      - --ciphertext-file=./storage/credentials/google/code-micro-videos.json.enc
      - --plaintext-file=./storage/credentials/google/code-micro-videos.json
      - --location=global
      - --keyring=testing
      - --key=service-account

  - id: "Rodando docker-compose"
    name: "gcr.io/$PROJECT_ID/docker-compose:1.24.0"
    args: ["-f","./docker-compose.prod.yaml","up","-d"]
    env:
      - GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID
      - GOOGLE_CLOUD_KEY_FILE=code-micro-videos.json
      - GOOGLE_CLOUD_STORAGE_BUCKET=micro_videos
      - GOOGLE_CLOUD_STORAGE_API_URI=https://storage.cloud.google.com/micro_video
      - TESTING_PROD=true

  - id: "Rodando docker ps"
    name: "gcr.io/cloud-builders/docker"
    args: ["ps"]

  - id: "Rodando composer"
    name: "gcr.io/cloud-builders/docker"
    args: ["exec", "-t", "app", "composer", "install"]

  - id: "Copiando .env"
    name: "gcr.io/cloud-builders/docker"
    args: ["exec", "-t", "app", "cp", ".env.example", ".env"]

  - id: "Copiando .env.testing"
    name: "gcr.io/cloud-builders/docker"
    args: ["exec", "-t", "app", "cp", ".env.testing.example", ".env.testing"]

  - id: "Rodando key Generate"
    name: "gcr.io/cloud-builders/docker"
    args: ["exec", "-t", "app", "php", "/var/www/artisan", "key:generate"]

  - id: "Rodando Migrations"
    name: "gcr.io/cloud-builders/docker"
    args: ["exec", "-t", "app", "php", "/var/www/artisan", "migrate"]

  - id: "Rodando Phpunit"
    name: "gcr.io/cloud-builders/docker"
    args: ["exec", "-t", "app", "php", "/var/www/vendor/bin/phpunit", "-c", "/var/www/phpunit.xml"]
